spec:
  name: essencepura
  services:
    - name: web
      environment_slug: node-js
      instance_size_slug: basic-xxs
      build_command: "npm ci && npm run build"
      run_command: "npm start"
      http_port: 3000
      routes:
        - path: /
      health_check:
        http_path: "/"
